services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=teste_gustavo_vinicius
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${CLOUD_DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

volumes:
  pgdata:
